### ISSUE TITLE
Scanner always timeout during plugin download 

### ISSUE THREAD

**Issue by vigneshraaj** [SonarSource/sonar-scanner-cli-docker#107]
Please ensure your issue adheres to the following guidelines: 
- [x] Please check the problem is not already reported
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

Image Used: sonarsource/sonar-scanner-cli:4.6
Command Used:
```
-Dsonar.host.url=https://sonarqube.domain.com 
-Dsonar.login="xxxxxxxxxxxxxxxxxxxxxxxxx" 
-Dsonar.projectKey=project-key 
-X
```

Output:
```
15:46:50.978 INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
15:46:50.982 INFO: Project root configuration file: NONE
15:46:51.044 INFO: SonarScanner 4.6.2.2472
15:46:51.045 INFO: Java 11.0.11 AdoptOpenJDK (64-bit)
15:46:51.045 INFO: Linux 5.10.25-linuxkit amd64
15:46:51.270 DEBUG: keyStore is : 
15:46:51.270 DEBUG: keyStore type is : pkcs12
15:46:51.271 DEBUG: keyStore provider is : 
15:46:51.271 DEBUG: init keystore
15:46:51.271 DEBUG: init keymanager of type SunX509
15:46:51.456 DEBUG: Create: /opt/sonar-scanner/.sonar/cache
15:46:51.457 INFO: User cache: /opt/sonar-scanner/.sonar/cache
15:46:51.457 DEBUG: Create: /opt/sonar-scanner/.sonar/cache/_tmp
15:46:51.461 DEBUG: Extract sonar-scanner-api-batch in temp...
15:46:51.466 DEBUG: Get bootstrap index...
15:46:51.466 DEBUG: Download: https://sonarqube.domain.com/batch/index
15:46:52.590 DEBUG: Get bootstrap completed
15:46:52.597 DEBUG: Download https://sonarqube.domain.com/batch/file?name=sonar-scanner-engine-shaded-8.9.0.43852-all.jar to /opt/sonar-scanner/.sonar/cache/_tmp/fileCache16445368501716957092.tmp
15:47:52.009 INFO: ------------------------------------------------------------------------
15:47:52.009 INFO: EXECUTION FAILURE
15:47:52.009 INFO: ------------------------------------------------------------------------
15:47:52.010 INFO: Total time: 1:01.044s
15:47:52.026 INFO: Final Memory: 3M/14M
15:47:52.026 INFO: ------------------------------------------------------------------------
15:47:52.026 ERROR: Error during SonarScanner execution
org.sonarsource.scanner.api.internal.ScannerException: Unable to execute SonarScanner analysis
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:85)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:74)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.createLauncher(IsolatedLauncherFactory.java:70)
	at org.sonarsource.scanner.api.EmbeddedScanner.doStart(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.start(EmbeddedScanner.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:73)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: Fail to download sonar-scanner-engine-shaded-8.9.0.43852-all.jar to /opt/sonar-scanner/.sonar/cache/_tmp/fileCache16445368501716957092.tmp
	at org.sonarsource.scanner.api.internal.cache.FileCache.download(FileCache.java:100)
	at org.sonarsource.scanner.api.internal.cache.FileCache.get(FileCache.java:84)
	at org.sonarsource.scanner.api.internal.JarDownloader.lambda$getScannerEngineFiles$0(JarDownloader.java:60)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.sonarsource.scanner.api.internal.JarDownloader.getScannerEngineFiles(JarDownloader.java:61)
	at org.sonarsource.scanner.api.internal.JarDownloader.download(JarDownloader.java:53)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherFactory.lambda$createLauncher$0(IsolatedLauncherFactory.java:76)
	... 7 more
Caused by: org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http2.StreamResetException: stream was reset: CANCEL
	at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:384)
	at org.sonarsource.scanner.api.internal.shaded.okhttp.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
	at org.sonarsource.scanner.api.internal.shaded.okio.RealBufferedSource$1.read(RealBufferedSource.java:447)
	at java.base/java.io.InputStream.transferTo(Unknown Source)
	at java.base/java.nio.file.Files.copy(Unknown Source)
	at org.sonarsource.scanner.api.internal.ServerConnection.downloadFile(ServerConnection.java:82)
	at org.sonarsource.scanner.api.internal.JarDownloader$ScannerFileDownloader.download(JarDownloader.java:73)
	at org.sonarsource.scanner.api.internal.cache.FileCache.download(FileCache.java:98)
	... 19 more

```

Always timing out in 60secs
Is there a way to increase the timeout?

/kind bug

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @vigneshraaj ,

you already found the way to our community forum and created a [post there](https://community.sonarsource.com/t/scanner-always-timeout-during-plugin-download/44291) right? 
i highly doubt that this issue related to the sonar-scanner-cli-docker image specifically and would like to close this issue here. if there is a reproducible issue identified in this thread we will track this with a jira ticket :slightly_smiling_face: 

>Is there a way to increase the timeout?

there is the `sonar.ws.timeout` analysis parameter that can be used for that
