### ISSUE TITLE
sonar-scanner-cli:5 java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: ClassRealm{ruby}

### ISSUE THREAD

**Issue by tcs-cclaflin** [SonarSource/sonar-scanner-cli-docker#189]
Have searched in this repo as well in the community forum. Testing moving to sonar-scanner-cli:5 docker image due to the java 11 -> 17 deprecation message.

When scanning a couple of our ruby application with the sonar-scanner-cli:4 docker image the scan runs without any errors but when running it with sonar-scanner-cli:5 docker image am seeing this error:

```
java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: ClassRealm{ruby}
        at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:225)
        at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:138)
        at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:97)
        at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:555)
        at org.joda.time.DateTimeZone.getProvider(DateTimeZone.java:449)
        at org.joda.time.DateTimeZone.forID(DateTimeZone.java:234)
        at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:169)
        at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
        at org.joda.time.base.BaseDateTime.<init>(BaseDateTime.java:97)
        at org.joda.time.DateTime.<init>(DateTime.java:209)
        at org.jruby.util.log.OutputStreamLogger.formatMessage(OutputStreamLogger.java:146)
        at org.jruby.util.log.StandardErrorLogger.write(StandardErrorLogger.java:58)
        at org.jruby.util.log.OutputStreamLogger.warn(OutputStreamLogger.java:67)
        at org.jruby.util.io.FilenoUtil$ReflectiveAccess.<clinit>(FilenoUtil.java:278)
        at org.jruby.util.io.FilenoUtil.getFilenoUsingReflection(FilenoUtil.java:143)
        at org.jruby.util.io.FilenoUtil.filenoFrom(FilenoUtil.java:139)
        at org.jruby.util.io.ChannelFD.initFileno(ChannelFD.java:51)
        at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:37)
        at org.jruby.util.io.ChannelFD.<init>(ChannelFD.java:47)
        at org.jruby.util.io.OpenFile.setChannel(OpenFile.java:195)
        at org.jruby.RubyIO.prepIO(RubyIO.java:263)
        at org.jruby.RubyIO.prepStdio(RubyIO.java:192)
        at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:314)
        at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:228)
        at org.jruby.Ruby.<init>(Ruby.java:513)
        at org.jruby.Ruby.newInstance(Ruby.java:716)
        at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:79)
        at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:69)
        at org.sonarsource.ruby.converter.RubyConverter.initializeRubyRuntime(RubyConverter.java:182)
        at org.sonarsource.ruby.converter.RubyConverter.<init>(RubyConverter.java:75)
        at org.sonarsource.ruby.converter.RubyConverter.<init>(RubyConverter.java:82)
        at org.sonarsource.ruby.plugin.RubySensor.astConverter(RubySensor.java:45)
        at org.sonarsource.slang.plugin.SlangSensor.execute(SlangSensor.java:201)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:62)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:75)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:66)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:48)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:64)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:123)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:109)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:468)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:464)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:420)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:123)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:109)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:128)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:123)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:109)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:57)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:51)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at jdk.proxy1/jdk.proxy1.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
        at org.sonarsource.scanner.cli.Main.main(Main.java:62)
2023-08-16T16:37:21.470Z [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
```

The scan goes ahead and completes and sends the results to sonarcloud.io.

Anything we need to do on our end or is this something in the image?

Thank you

**Comment by carminevassallo** [comment]
Dear @tcs-cclaflin,

Thanks for reporting this issue! As you might have noticed in the `README.md`, we are trying to centralize the management of all bug reports and feature requests related to Sonar products in our [forum](https://community.sonarsource.com/).

If you think this issue is still relevant, could you please post it there? In the meantime, I'm closing it.
