### ISSUE TITLE
java.lang.IllegalStateException: Fail to instantiate class [com.github.sbaudoin.sonar.plugins.yaml.YamlPlugin] of plugin [yaml]

### ISSUE THREAD

**Issue by derhecht** [SonarSource/sonar-scanner-cli-docker#72]
we're using the image in our jenkins pipeline
`docker.image('sonarsource/sonar-scanner-cli').inside {
        withSonarQubeEnv() {
            sh "sonar-scanner -Dsonar.projectBaseDir=" + env.WORKSPACE
    }`

Stacktrace
`INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /var/lib/jenkins/jobs/.../workspace/sonar-project.properties
INFO: SonarScanner 4.3.0.2102
INFO: Java 11.0.3 AdoptOpenJDK (64-bit)
INFO: Linux 4.9.0-12-amd64 amd64
INFO: User cache: ?/.sonar/cache
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /var/lib/jenkins/jobs/.../workspace/sonar-project.properties
INFO: Analyzing on SonarQube server 7.9.2
INFO: Default locale: "en_US", source code encoding: "US-ASCII" (analysis is platform dependent)
INFO: Load global settings
INFO: Load global settings (done) | time=270ms
INFO: Server id: 46AF5D23-1352d10a5eafaf3
INFO: User cache: /var/lib/jenkins/jobs/.../workspace/?/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=72ms
INFO: Plugin [l10nde] defines 'l10nen' as base plugin. This metadata can be removed from manifest of l10n plugins since version 5.2.
INFO: Load/download plugins (done) | time=3578ms
WARN: API compatibility mode is no longer supported. In case of error, plugin German Pack [l10nde] should package its dependencies.
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 6.515s
INFO: Final Memory: 9M/48M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Fail to instantiate class [com.github.sbaudoin.sonar.plugins.yaml.YamlPlugin] of plugin [yaml]
	at org.sonar.core.platform.PluginLoader.instantiatePluginClasses(PluginLoader.java:136)
	at org.sonar.core.platform.PluginLoader.load(PluginLoader.java:66)
	at org.sonar.scanner.bootstrap.ScannerPluginRepository.start(ScannerPluginRepository.java:61)
	at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.NoClassDefFoundError: org/reflections/Reflections
	at com.github.sbaudoin.sonar.plugins.yaml.YamlPlugin.<init>(YamlPlugin.java:35)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at org.sonar.core.platform.PluginLoader.instantiatePluginClasses(PluginLoader.java:131)
	... 26 more
Caused by: java.lang.ClassNotFoundException: org.reflections.Reflections
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 33 more
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.`

What does this want me to tell?

Please ensure your issue adheres to the following guidelines: 
- [ x ] Please check the problem is not already reported
- [ x ] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

**Comment by derhecht** [comment]
looks like this could be a cache issue ("?" folder maybe a bit tricky) as Sonar downloads plugins on demand from server, am I right?

**Comment by derhecht** [comment]
ok, looks like it was fixed with newest version
